# Generated by Django 4.0.2 on 2022-02-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_movie_mpa_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
