# Generated by Django 4.0.2 on 2022-02-03 17:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_directors_movie_stars_movie_writers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('director', 'director'), ('writer', 'writer'), ('actor', 'actor')], max_length=8),
        ),
    ]
