# Generated by Django 4.0.2 on 2022-02-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_person_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bg_picture',
            field=models.FileField(default=1, upload_to='bg_picture/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.FileField(default=1, upload_to='poster/'),
            preserve_default=False,
        ),
    ]
